### ISSUE TITLE
CLion 中文乱码问题解决方案 （无需修改 Windows 设置）

### ISSUE THREAD

**Issue by mcdd0506** [CarmJos/CWorks#1]
> [!CAUTION]
> 旧解决方案：
>
> 对于新版的 Windows 11 我们可以手动在设置中将操作系统的编码调整为 UTF-8，这样文件源码以及控制台终端编码都统一为 UTF-8 肯定就没问题了，但是这样会导致其他一些软件乱码 (视频中有提及该操作会导致其它软件无法运行)

新的解决方案 （可用）

1. 打开 CLion 双击 Shift，在弹出的搜索栏中，输入`Registry`，然后点击 `Registry…` 进入软件注册表界面

![Snipaste_2024-07-27_18-40-09](https://github.com/user-attachments/assets/cea51dec-529f-468f-bd6d-4d777ee9b26e)

2. 取消勾选 `run.processes.with.pty` 

![Snipaste_2024-07-27_18-41-50](https://github.com/user-attachments/assets/44a0645f-940c-4f20-b449-c344cbbd24ba)

效果：

![Snipaste_2024-07-27_18-41-23](https://github.com/user-attachments/assets/06e70e62-6611-4eca-8446-ef73e74f322a)

参考自：
- https://cloud.tencent.com/developer/article/2135061

**Comment by mcdd0506** [comment]
项目编码配置

![Snipaste_2024-07-27_18-44-15](https://github.com/user-attachments/assets/d8e866f2-2596-403f-9311-8b18f0e18aa4)

**Comment by CarmJos** [comment]
这个方案当初我也试过，但是忘记了为什么最后放弃了这个做法。

于是我实际测试了一下，这样可能会导致输出的内容延后，从而无法正常的测试。
![image](https://github.com/user-attachments/assets/ed1a69c7-c8d3-44f6-9224-aabf56601ed4)

（评论区也存在同样问题，现在知道为什么会出这个问题了）

![image](https://github.com/user-attachments/assets/ad5d7955-215d-4e49-be3b-8c9748312ab5)

**Comment by CarmJos** [comment]
总体来说，目前最好的解决方案可能还是更换cygwin编译器。

**Comment by mcdd0506** [comment]
感谢 🙇‍
